/*
 * HERE I WISH TO DO SOMETHING SIMILAR TO KYSLEY, WHERE A DEVELOPER IS ABLE TO DEFINE THEIR TABLES WITHIN A TYPE, AND ALSO DEFINE THEIR TABLES DATA AND DATATYPES
 * ENSURING THAT THERE IS TYPESCRIPT SUPPORT!
*/

namespace DatabaseTypes {
  interface Database {
  
  }

}
